## pagination input
input Pagination {
    page: Int
    limit: Int
}

input Sort {
    byDate: SortOptions
    byName: SortOptions
}

## enum types
enum SortOptions {
    toLargest
    toSmallest
}
enum Bool {
    TRUE
    FALSE
}

type MutationResponse {
  status: Int!
  message: String!
}


type AuthResponse {
  status: Int!
  message: String!
  token: String
  data: Stuff!
}

union GlobalType = Stuff | Branch | AuthResponse
