type Query {
    branches(
        pagination: Pagination
        search: String
        sort: Sort
    ): [Branch!]!
    branch(branch_id: ID!): Branch!
}

type Branch {
    branch_id: ID!
    branch_name: String!
    branch_address: String!
    time_created: String!
}
type Mutation {
    addBranch(
        stuff_id: ID!
        branch_name: String!
        branch_address: String!
    ): MutationResponse!
    changeBranch(
        stuff_id: ID!
        branch_id: ID!
        branch_name: String!
        branch_address: String!
    ): MutationResponse!
    deleteBranch(
        stuff_id: ID!
        branch_id: ID!
    ): MutationResponse!
}